name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
      - run: |
          git add .
          git commit -m "heroku commit"
          heroku git:remote -a Ywhatisupandwhatisdown
          git push heroku master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "whatisupandwhatisdown"
          heroku_email: ${{secrets.HEROKU_EMAIL}}